workflows:

  version: 2
  test_and_packaging:

    jobs:
      - test
      - dockerize:
         requires:
           - test
      - build:
         requires:
           - dockerize

jobs:
  test:
    docker:
      - image: sebastiansc/pythonapp:latest
    steps:
      - checkout
      - run:
          name: test
          command: |
            mkdir test-out
            python tests.py
      - store_test_results:
          path: /test-out/
      - store_artifacts:
          path: .
          destination: prefix

  
  dockerize:
    machine: true
    steps:
      - checkout
      # Login to docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # build the application image
      - run: docker build -t $DOCKER_USER/pythonapp:$CIRCLE_SHA1 .

      # deploy the image
      - run: docker push $DOCKER_USER/pythonapp:$CIRCLE_SHA1
  
  build:
    machine: true
    docker:
      - image: sebastiansc/pythonapp:$CIRCLE_SHA1
    steps:
      - checkout
      - run:
          name: build
          command: |
            mkdir build-out
            docker run -d $DOCKER_USER/myapp:$CIRCLE_SHA1 
      - store_artifacts:
          path: /build-out/
          destination: output      
