workflows:

  version: 2
  test_and_packaging:

    jobs:
      - test
      
jobs:
  test:
    docker:
      - image: sebastiansc/pythonapp:latest
    steps:
      - checkout
      - run:
          name: Build and test
          command:
            python tests.py
      - store_test_results:
          path: build/test-results
          destination: prefix
      - persist_to_workspace:
          root: .
          paths: .
