workflows:

  version: 2
  test_and_packaging:

    jobs:
      - package
      - test:
         requires:
           - package
      - dockerize:
         requires:
           - test
      
jobs:
  package:
    docker:
      - image: sebastiansc/pythonapp:latest
    steps:
      - checkout
      - run:
         name: package and push
         command:
           docker build -t sebastiansc/pythonapp:latest .
      - store_artifacts:
          path: .
          destination: output
  
  test:
    docker:
      - image: sebastiansc/pythonapp:latest
    steps:
      - checkout
      - run:
          name: Build and test
          command:
            python tests.py
      - store_test_results:
          path: .
      - store_artifacts:
          path: .
          destination: prefix

  
  dockerize:
    machine: true
    steps:
      - checkout
      # Login to docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # build the application image
      - run: docker build -t $DOCKER_USER/pythonapp:$CIRCLE_SHA1 .

      # deploy the image
      - run: docker push $DOCKER_USER/pythonapp:$CIRCLE_SHA1
