workflows:

  version: 2
  test_and_packaging:

    jobs:
      - package
      - test:
          requires:
            - package
      
jobs:
  test:
    docker:
      - image: sebastiansc/python:latest
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - my-dependencies-{{ checksum "build.gradle" }}
      - checkout
      - run:
          name: Build and test
          command:
            python test.py
      - store_test_results:
          path: build/test-results
      
     


  package:
    docker:
      - image: sebastiansc/python:latest
    steps:
      - checkout
      - run:
          name: Package and store Artifacts
          command:
            python run.py
      - store_artifacts:
          path: build/libs
          destination: output
      - persist_to_workspace:
          root: .
          paths:
            - .
      - save_cache:
          key: my-dependencies-{{ checksum "build.gradle" }}
          paths:
            - my-project/my-dependencies-directory
