workflows:

  version: 2
  test_and_packaging:

    jobs:
      - test
      
jobs:
  test:
    docker:
      - image: sebastiansc/pythonapp:latest
    steps:
      - checkout
      - run:
          name: Build and test
          command:
            python tests.py
      - store_test_results:
          path: .
      - store_artifacts:
          path: .
          destination: prefix

  
