workflows:
 
  version: 2
  test_and_packaging:

    jobs:
      - test
      - dockerize:
         requires:
           - test
      - ssh:
         requires:
           - dockerize

jobs:
  test:
    docker:
      - image: sebastiansc/pythonapp:latest
    steps:
      - checkout
      - run:
          name: mkdir
          command:
            mkdir test-out
      - run:
          name: test
          command:
            python tests.py
      - store_test_results:
          path: /test-out/
      - store_artifacts:
          path: .
          destination: test-artifacts

  
  dockerize:
    machine: true
    steps:
      - checkout
      # Login to docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # build the application image
      - run: docker build -t $DOCKER_USER/pythonapp:$CIRCLE_SHA1 .

      # deploy the image
      - run: docker push $DOCKER_USER/pythonapp:$CIRCLE_SHA1
      - store_artifacts:
          path: .
          destination: docker-artifacts
  
  ssh:
    docker:
      - image: gotechnies/alpine-ssh
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bc:b2:8d:c5:3c:61:9e:44:93:37:a3:2b:cf:36:09:a2"
      - run:
             ssh -i ubuntu@35.240.114.104 "docker run -d $DOCKER_USER/myapp:$CIRCLE_SHA1" -y 
      - store_artifacts:
          path: .
          destination: ssh-output
