workflows:

  version: 2
  test_and_packaging:

    jobs:
      - test
      
jobs:
  test:
    docker:
      - image: sebastiansc/pythonapp:latest
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - my-dependencies-{{ checksum "build.gradle" }}
      - checkout
      - run:
          name: Build and test
          command:
            python test.py
      - store_test_results:
          path: build/test-results
